service: serverless-simple-http-endpoint

plugins:
  - serverless-offline

provider:
  name: aws
  stage: ${env:NODE_ENV, "development"}
  runtime: nodejs12.x
  environment:
    NODE_ENV: ${self:provider.stage}

custom:
  serverless-offline:
    httpPort: 8006
    noPrependStageInUrl: true

package:
  individually: true

functions:
  currentTime:
    handler: index.handler
    events:
      - http:
          path: /time
          method: get